export const TECH_STACK_IMAGES = {
  AngularJS: "images/tech-stack/angular.webp",
  AWS: "images/tech-stack/aws.svg",
  ReactJS: "images/tech-stack/reactjs.webp",
  TailwindCSS: "images/tech-stack/tailwindcss.svg",
  MongoDB: "images/tech-stack/mongodb.svg",
  NodeJS: "images/tech-stack/nodejs.webp",
  TensorFlow: "images/tech-stack/tensorflow.svg",
  OpenCV: "images/tech-stack/opencv.svg",
  OpenAI: "images/tech-stack/openai.svg",
  Python: "images/tech-stack/python.svg",
  DeepFace: "images/tech-stack/deepface.webp",
  HuggingFace: "images/tech-stack/hugging-face.webp",
  Lucid: "",
  Java: "images/tech-stack/java.webp",
  Firebase: "images/tech-stack/firebase.svg",
  Javascript: "images/tech-stack/javascript.svg",
  "IBM Watson": "",
  NodeRED: "images/tech-stack/node-red.svg",
  Scala: "images/tech-stack/scala.svg",
  Swift: "images/tech-stack/swift.webp",
  Realm: "images/tech-stack/realm.svg",
  Wix: "images/tech-stack/wix.svg",
  humanPowered: "",
};
