identifier: l598tcp54aq2g59e
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: sean-chen
homeFolder: /Users/Sean/Desktop/Work/SUTD/Projects/seancze-website
distFolder: ./dist/sean-chen
outDir: /Users/Sean/Desktop/Work/SUTD/Projects/seancze-website/vercel/output
handle404: ''
allowErrorCollect: false
